### ISSUE TITLE
Replace `getDetails` with `toString`?

### ISSUE THREAD

**Issue by thgaskell** [devleague/js-constructors#11]
Would there be any use in having people overriding the default `Object.prototype.toString` method? The `getDetails` method acts exactly the same as `toString`, but I'm not entirely sure if that makes sense to have the `toString` value actually contain all that information?

**Comment by theRemix** [comment]
Do you mean redefining the global `Object.prototype.toString` ?
The author should not be advised to adopt overriding globals, that may turn into a nasty habit. 
Suggest to implement a `mixin` style prototype method per class vs. overriding the global Object class.

```
function getDetails(){ ... }
MyParentClass.prototype.getDetails = getDetails;
// inherited MyChildClass.prototype.getDetails = getDetails;
MyOtherClass.prototype.getDetails = getDetails;
```
redefining `toString` on the class definition is also acceptable
```
function getDetails(){ ... }
MyParentClass.prototype.toString = getDetails;
// inherited MyChildClass.prototype.toString = getDetails;
MyOtherClass.prototype.toString = getDetails;
```

**Comment by jaywon** [comment]
I don't see any problem with overriding the toString() method directly on the class as that's fairly standard. Every class has the base functionality until you want more out of it and then you override for that class. This was common practice in C# world.

**Comment by thgaskell** [comment]
@theRemix I mean setting `Spell.prototype.toString()`. The more I think about it though, it's invoked whenever a string value is expected. I thought it would actually get invoked internally when `console.log` is called on an instance, but it doesn't look like that's the case.

## Class definition
```javascript
class Spell {
  constructor (name, cost, description) {
    this.name = name;
    this.cost = cost;
    this.description = description;
  }
  toString() {
    return `${this.name} [${this.cost}] – ${this.description}`
  }
}
```
## Usage
```javascript
let fireball = new Spell('Fireball', 10, 'It burns.');
console.log(fireball);  // Spell {name: "Fireball", cost: 10, description: "It burns."}
console.log(fireball.toString());  // "Fireball [10] – It burns."
console.log(`Casting ${fireball}`)  //"Casting Fireball [10] – It burns."
```

In the last case, it more sense to me if it were to say `"Casting Fireball"`. I haven't implemented the `toString` before, are there any guidelines of when and when not to do it?

**Comment by jaywon** [comment]
Here is kind of what i refer to in C#: http://stackoverflow.com/a/10278430/202105

I think it's one of those things you make a conscious design decision about an entire application needing richer logging that people can depend on throughout a large OOP implementation, regardless of particular class, as opposed to a "best practice" of things to do always in OOP.
